name: NILM MVP
version: "0.1.2"
slug: nilm_mvp
description: "Einfaches NILM Add-on"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: application
boot: auto
options:
  sample_interval_s: 3
schema:
  sample_interval_s: int
